name: Build on Ubuntu 20.04

permissions: write-all

on:
  push:
    branches: [ deb_pack ]

  pull_request:
    branches: [ deb_pack ]

  workflow_dispatch:

jobs:
  ubuntu22:
    name: ubuntu-22.04
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Update repository
      run: sudo apt-get update -y

    - name: Install the basic dev packages
      run: sudo apt-get install -y equivs curl git devscripts lintian build-essential automake autotools-dev cmake g++
    
    - name: Install build dependencies
      run: sudo mk-build-deps -i -t "apt-get --yes" -r

    - name: Build Package
      run: |
        sudo dpkg-buildpackage -b -uc -us -j$(nproc)

    - name: Pack artifacts
      run: |
        mkdir -p artifacts
        mv ../*.deb artifacts

    - uses: actions/upload-artifact@v4
      with:
        name: FluentUI Artifacts 22
        path: artifacts
        compression-level: 9 # maximum compression

  ubuntu24:
    name: ubuntu-24.04
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Update repository
      run: sudo apt-get update -y

    - name: Install the basic dev packages
      run: sudo apt-get install -y equivs curl git devscripts lintian build-essential automake autotools-dev cmake g++
    
    - name: Install build dependencies
      run: sudo mk-build-deps -i -t "apt-get --yes" -r

    - name: Build Package
      run: |
        dpkg-buildpackage -b -uc -us -j$(nproc)

    - name: Pack artifacts
      run: |
        mkdir -p artifacts
        mv ../*.deb artifacts

    - uses: actions/upload-artifact@v4
      with:
        name: FluentUI Artifacts 24
        path: artifacts
        compression-level: 9 # maximum compression
  
